apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: source
  steps:
    - name: remove
      image: alpine:3
      env:
        - name: WORKSPACE_SOURCE_PATH
          value: $(workspaces.source.path)
      workingDir: $(workspaces.source.path)
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      script: |
        #!/usr/bin/env sh
        set -eu
        echo "Removing all files from ${WORKSPACE_SOURCE_PATH} ..."
        if [ -d "${WORKSPACE_SOURCE_PATH}" ] ; then
          rm -rf "${WORKSPACE_SOURCE_PATH:?}"/*
          rm -rf "${WORKSPACE_SOURCE_PATH}"/.[!.]*
          rm -rf "${WORKSPACE_SOURCE_PATH}"/..?*
        fi
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: jest-test
spec:
  workspaces:
    - name: source
  params:
    - name: args
      description: Arguments to pass to jest
      type: string
      default: "-v"
  steps:
    - name: jest
      image: node:20-alpine
      workingDir: $(workspaces.source.path)
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      script: |
        #!/bin/sh
        set -e
        echo "Cleaning node_modules if exists..."
        rm -rf node_modules
        echo "Installing dependencies..."
        npm ci --prefer-offline --no-audit
        echo "Running Jest tests..."
        npm test $(params.args)
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: eslint
spec:
  workspaces:
    - name: source
  steps:
    - name: lint
      image: node:20-alpine
      workingDir: $(workspaces.source.path)
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      script: |
        #!/bin/sh
        set -e
        echo "Cleaning node_modules if exists..."
        rm -rf node_modules
        echo "Installing dependencies..."
        npm ci --prefer-offline --no-audit
        echo "Running ESLint..."
        npm run lint
